Add hold configurator
a-givertzman/sss-computing-client pull request #56
Opened 2024-09-02 15:52 UTC by nyaneet

Closes #52

2024-09-11 10:06 UTC, a-givertzman requested changes
Check some comments in review about code quality, briefly:
- Try to fix / extend meaningless doc-comments
- try to avoid code duplication
- try to move/have functionality such as parsing `json` into the corresponding object
- try to avoid literals sparsed in whole code
- try ti decrease number of public methods
In generally - nice huge work, thank you!

2024-09-17 11:45 UTC, a-givertzman commented on lib/core/models/bulkheads/pg_bulkhead_places.dart
> +      entryBuilder: (row) => JsonBulkheadPlace(
discussed

2024-09-23 15:58 UTC, nyaneet commented on lib/core/models/field/field_type.dart
> +/// Enum of FieldData value types
Fixed in b71e9effe7824a166fda63e66ae45bbd09bed226

2024-09-23 16:08 UTC, nyaneet commented on lib/core/models/bulkheads/json_bulkhead.dart
> +  /// Creates [Bulkhead] that parses itself from provided `json` map.
Fixed in fdec20a4aa264faef2d8f63a21f3c7a6951bc9cd for whole project
It turned out to be easy, based on regular expressions and vs code replace feature (e.g. ``` `([a-zA-Z]) ``` in search pattern and ``` $1[ ``` in replace expression for ``` ` ``` symbol followed by any letter)

Correctness of fix verified based on [Effective Dart: Documentation](https://dart.dev/effective-dart/documentation#do-use-square-brackets-in-doc-comments-to-refer-to-in-scope-identifiers)

2024-09-23 16:14 UTC, nyaneet commented
Added documentation as submodule in 93bab0e30b9e73bbd52d181dac5ba7c10d21c43c

2024-10-21 12:26 UTC, a-givertzman submitted a review, later dismissed

2024-10-21 14:07 UTC, merged